apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-qvdhjtxp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-qvdhjtxp:f2b4eba599cb0a6596fe138736c78487de18b51a@sha256:3b49090c18e3d0fb79aad15f958c9445c52785c289be0d8afa47f1bcfd7ec14d
          name: container-image
